export const SET_PAGETYPE = 'SET_PAGETYPE';

export const FETCH_FORCES = 'FETCH_FORCES';
export const SET_FORCES_ARRAY = 'SET_FORCES_ARRAY';

export const SET_ATTACKERRACE = 'SET_ATTACKERRACE';
export const SET_ATTACKERUNIT = 'SET_ATTACKERUNIT';
export const SET_ATTACKERUNIT_ARRAY = 'SET_ATTACKERUNIT_ARRAY';
export const SET_ATTACKER_STATS_COLLECTION = 'SET_ATTACKER_STATS_COLLECTION';
export const CLEAR_ATTACKER_STATS_COLLECTION = 'CLEAR_ATTACKER_STATS_COLLECTION';
export const SET_ATTACKER_SAVE_UNITS = 'SET_ATTACKER_SAVE_UNITS';
export const FETCH_ATTACKER_UNIT_STATS = 'FETCH_ATTACKER_UNIT_STATS';
export const FETCH_ATTACKER_UNITS = 'FETCH_ATTACKER_UNITS';

export const SET_DEFENDERRACE = 'SET_DEFENDERRACE';
export const SET_DEFENDERUNIT = 'SET_DEFENDERUNIT';
export const SET_DEFENDERUNIT_ARRAY = 'SET_DEFENDERUNIT_ARRAY';
export const SET_DEFENDER_SAVE_UNITS = 'SET_DEFENDER_SAVE_UNITS';
export const SET_DEFENDEFR_STATS_COLLECTION = 'SET_DEFENDEFR_STATS_COLLECTION';
export const FETCH_DEFENDER_UNIT_STATS = 'FETCH_DEFENDER_UNIT_STATS';
export const FETCH_DEFENDER_UNITS = 'FETCH_DEFENDER_UNITS';

export const SET_ATTACKER_UNIT_STATS = 'SET_ATTACKER_UNIT_STATS';
export const CLEAR_ATTACKER_UNIT_STATS = 'CLEAR_ATTACKER_UNIT_STATS';
export const SET_DEFENDER_UNIT_STATS = 'SET_DEFENDER_UNIT_STATS';
export const CLEAR_DEFENDER_UNIT_STATS = 'CLEAR_DEFENDER_UNIT_STATS';

export const SET_ATTACKER_CHOOSED_DATA = 'SET_ATTACKER_CHOOSED_DATA';
export const SET_DEFENDER_CHOOSED_DATA = 'SET_DEFENDER_CHOOSED_DATA';

