export const FETCH_FORCES = 'FETCH_FORCES';
export const FETCH_ALL_UNITS = 'FETCH_ALL_UNITS';
export const SET_PAGETYPE = 'SET_PAGETYPE';
export const SET_ATTACKERRACE = 'SET_ATTACKERRACE';
export const SET_ATTACKERUNIT = 'SET_ATTACKERUNIT';
export const SET_DEFENDERRACE = 'SET_DEFENDERRACE';
export const SET_DEFENDERUNIT = 'SET_DEFENDERUNIT';